// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file backup.proto (package timetable, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file backup.proto.
 */
export const file_backup: GenFile = /*@__PURE__*/
  fileDesc("CgxiYWNrdXAucHJvdG8SCXRpbWV0YWJsZSIpCg9Mb2NhbGl6ZWRTdHJpbmcSCgoCZW4YASABKAkSCgoCa2EYAiABKAkiUwoOQmFja3VwRW52ZWxvcGUSFgoOc2NoZW1hX3ZlcnNpb24YASABKA0SKQoHcGF5bG9hZBgCIAEoCzIYLnRpbWV0YWJsZS5CYWNrdXBQYXlsb2FkIr4CCg1CYWNrdXBQYXlsb2FkEiIKB2NvdXJzZXMYASADKAsyES50aW1ldGFibGUuQ291cnNlEjAKDGRheV9zZXR0aW5ncxgCIAMoCzIaLnRpbWV0YWJsZS5EYXlTZXR0aW5nRW50cnkSJgoLZ2xvYmFsX3RpbWUYAyABKAsyES50aW1ldGFibGUuTWluTWF4EioKD2NsYXNzZXNfcGVyX2RheRgEIAEoCzIRLnRpbWV0YWJsZS5NaW5NYXgSEwoLbWF4X292ZXJsYXAYBSABKA0SKAoNZGFpbHlfY29tbXV0ZRgGIAEoCzIRLnRpbWV0YWJsZS5NaW5NYXgSLwoObGVjdHVyZXJfcHJlZnMYByADKAsyFy50aW1ldGFibGUuTGVjdHVyZXJQcmVmEhMKC3RpbWVfZm9ybWF0GAggASgJIp0CCgZDb3Vyc2USEwoLY291cnNlX25hbWUYASABKAkSFAoMc3ViamVjdF9jb2RlGAIgASgJEiAKBmdyb3VwcxgDIAMoCzIQLnRpbWV0YWJsZS5Hcm91cBIRCglpc19hY3RpdmUYBCABKAgSFAoMbG9ja2VkX2dyb3VwGAUgASgJEhcKD2V4Y2x1ZGVkX2dyb3VwcxgGIAMoCRINCgVvcmRlchgHIAEoDRI5ChVjb3Vyc2VfbmFtZV9sb2NhbGl6ZWQYCCABKAsyGi50aW1ldGFibGUuTG9jYWxpemVkU3RyaW5nEjoKFnN1YmplY3RfY29kZV9sb2NhbGl6ZWQYCSABKAsyGi50aW1ldGFibGUuTG9jYWxpemVkU3RyaW5nIrcBCgVHcm91cBIMCgRuYW1lGAEgASgJEhAKCGxlY3R1cmVyGAIgASgJEiIKBXRpbWVzGAMgAygLMhMudGltZXRhYmxlLlRpbWVTbG90EjIKDm5hbWVfbG9jYWxpemVkGAQgASgLMhoudGltZXRhYmxlLkxvY2FsaXplZFN0cmluZxI2ChJsZWN0dXJlcl9sb2NhbGl6ZWQYBSABKAsyGi50aW1ldGFibGUuTG9jYWxpemVkU3RyaW5nImcKCFRpbWVTbG90EgsKA2RheRgBIAEoDRIMCgR0aW1lGAIgASgJEgwKBHJvb20YAyABKAkSMgoOcm9vbV9sb2NhbGl6ZWQYBCABKAsyGi50aW1ldGFibGUuTG9jYWxpemVkU3RyaW5nIjAKDExlY3R1cmVyUHJlZhIQCghsZWN0dXJlchgBIAEoCRIOCgZ3ZWlnaHQYAiABKAkiIgoGTWluTWF4EgsKA21pbhgBIAEoAhILCgNtYXgYAiABKAIiRgoPRGF5U2V0dGluZ0VudHJ5EgsKA2RheRgBIAEoDRImCgdzZXR0aW5nGAIgASgLMhUudGltZXRhYmxlLkRheVNldHRpbmcigwEKCkRheVNldHRpbmcSDAoEcHJlZhgBIAEoCRILCgNtaW4YAiABKA0SCwoDbWF4GAMgASgNEisKDGJ1c3lfcGVyaW9kcxgEIAMoCzIVLnRpbWV0YWJsZS5CdXN5UGVyaW9kEhQKB2NvbW11dGUYBSABKAJIAIgBAUIKCghfY29tbXV0ZSIoCgpCdXN5UGVyaW9kEg0KBXN0YXJ0GAEgASgNEgsKA2VuZBgCIAEoDWIGcHJvdG8z");

/**
 * @generated from message timetable.LocalizedString
 */
export type LocalizedString = Message<"timetable.LocalizedString"> & {
  /**
   * @generated from field: string en = 1;
   */
  en: string;

  /**
   * @generated from field: string ka = 2;
   */
  ka: string;
};

/**
 * Describes the message timetable.LocalizedString.
 * Use `create(LocalizedStringSchema)` to create a new message.
 */
export const LocalizedStringSchema: GenMessage<LocalizedString> = /*@__PURE__*/
  messageDesc(file_backup, 0);

/**
 * @generated from message timetable.BackupEnvelope
 */
export type BackupEnvelope = Message<"timetable.BackupEnvelope"> & {
  /**
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * @generated from field: timetable.BackupPayload payload = 2;
   */
  payload?: BackupPayload;
};

/**
 * Describes the message timetable.BackupEnvelope.
 * Use `create(BackupEnvelopeSchema)` to create a new message.
 */
export const BackupEnvelopeSchema: GenMessage<BackupEnvelope> = /*@__PURE__*/
  messageDesc(file_backup, 1);

/**
 * @generated from message timetable.BackupPayload
 */
export type BackupPayload = Message<"timetable.BackupPayload"> & {
  /**
   * @generated from field: repeated timetable.Course courses = 1;
   */
  courses: Course[];

  /**
   * @generated from field: repeated timetable.DaySettingEntry day_settings = 2;
   */
  daySettings: DaySettingEntry[];

  /**
   * @generated from field: timetable.MinMax global_time = 3;
   */
  globalTime?: MinMax;

  /**
   * @generated from field: timetable.MinMax classes_per_day = 4;
   */
  classesPerDay?: MinMax;

  /**
   * @generated from field: uint32 max_overlap = 5;
   */
  maxOverlap: number;

  /**
   * @generated from field: timetable.MinMax daily_commute = 6;
   */
  dailyCommute?: MinMax;

  /**
   * @generated from field: repeated timetable.LecturerPref lecturer_prefs = 7;
   */
  lecturerPrefs: LecturerPref[];

  /**
   * @generated from field: string time_format = 8;
   */
  timeFormat: string;
};

/**
 * Describes the message timetable.BackupPayload.
 * Use `create(BackupPayloadSchema)` to create a new message.
 */
export const BackupPayloadSchema: GenMessage<BackupPayload> = /*@__PURE__*/
  messageDesc(file_backup, 2);

/**
 * @generated from message timetable.Course
 */
export type Course = Message<"timetable.Course"> & {
  /**
   * @generated from field: string course_name = 1;
   */
  courseName: string;

  /**
   * @generated from field: string subject_code = 2;
   */
  subjectCode: string;

  /**
   * @generated from field: repeated timetable.Group groups = 3;
   */
  groups: Group[];

  /**
   * @generated from field: bool is_active = 4;
   */
  isActive: boolean;

  /**
   * @generated from field: string locked_group = 5;
   */
  lockedGroup: string;

  /**
   * @generated from field: repeated string excluded_groups = 6;
   */
  excludedGroups: string[];

  /**
   * @generated from field: uint32 order = 7;
   */
  order: number;

  /**
   * @generated from field: timetable.LocalizedString course_name_localized = 8;
   */
  courseNameLocalized?: LocalizedString;

  /**
   * @generated from field: timetable.LocalizedString subject_code_localized = 9;
   */
  subjectCodeLocalized?: LocalizedString;
};

/**
 * Describes the message timetable.Course.
 * Use `create(CourseSchema)` to create a new message.
 */
export const CourseSchema: GenMessage<Course> = /*@__PURE__*/
  messageDesc(file_backup, 3);

/**
 * @generated from message timetable.Group
 */
export type Group = Message<"timetable.Group"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string lecturer = 2;
   */
  lecturer: string;

  /**
   * @generated from field: repeated timetable.TimeSlot times = 3;
   */
  times: TimeSlot[];

  /**
   * @generated from field: timetable.LocalizedString name_localized = 4;
   */
  nameLocalized?: LocalizedString;

  /**
   * @generated from field: timetable.LocalizedString lecturer_localized = 5;
   */
  lecturerLocalized?: LocalizedString;
};

/**
 * Describes the message timetable.Group.
 * Use `create(GroupSchema)` to create a new message.
 */
export const GroupSchema: GenMessage<Group> = /*@__PURE__*/
  messageDesc(file_backup, 4);

/**
 * @generated from message timetable.TimeSlot
 */
export type TimeSlot = Message<"timetable.TimeSlot"> & {
  /**
   * @generated from field: uint32 day = 1;
   */
  day: number;

  /**
   * @generated from field: string time = 2;
   */
  time: string;

  /**
   * @generated from field: string room = 3;
   */
  room: string;

  /**
   * @generated from field: timetable.LocalizedString room_localized = 4;
   */
  roomLocalized?: LocalizedString;
};

/**
 * Describes the message timetable.TimeSlot.
 * Use `create(TimeSlotSchema)` to create a new message.
 */
export const TimeSlotSchema: GenMessage<TimeSlot> = /*@__PURE__*/
  messageDesc(file_backup, 5);

/**
 * @generated from message timetable.LecturerPref
 */
export type LecturerPref = Message<"timetable.LecturerPref"> & {
  /**
   * @generated from field: string lecturer = 1;
   */
  lecturer: string;

  /**
   * @generated from field: string weight = 2;
   */
  weight: string;
};

/**
 * Describes the message timetable.LecturerPref.
 * Use `create(LecturerPrefSchema)` to create a new message.
 */
export const LecturerPrefSchema: GenMessage<LecturerPref> = /*@__PURE__*/
  messageDesc(file_backup, 6);

/**
 * @generated from message timetable.MinMax
 */
export type MinMax = Message<"timetable.MinMax"> & {
  /**
   * @generated from field: float min = 1;
   */
  min: number;

  /**
   * @generated from field: float max = 2;
   */
  max: number;
};

/**
 * Describes the message timetable.MinMax.
 * Use `create(MinMaxSchema)` to create a new message.
 */
export const MinMaxSchema: GenMessage<MinMax> = /*@__PURE__*/
  messageDesc(file_backup, 7);

/**
 * @generated from message timetable.DaySettingEntry
 */
export type DaySettingEntry = Message<"timetable.DaySettingEntry"> & {
  /**
   * @generated from field: uint32 day = 1;
   */
  day: number;

  /**
   * @generated from field: timetable.DaySetting setting = 2;
   */
  setting?: DaySetting;
};

/**
 * Describes the message timetable.DaySettingEntry.
 * Use `create(DaySettingEntrySchema)` to create a new message.
 */
export const DaySettingEntrySchema: GenMessage<DaySettingEntry> = /*@__PURE__*/
  messageDesc(file_backup, 8);

/**
 * @generated from message timetable.DaySetting
 */
export type DaySetting = Message<"timetable.DaySetting"> & {
  /**
   * @generated from field: string pref = 1;
   */
  pref: string;

  /**
   * @generated from field: uint32 min = 2;
   */
  min: number;

  /**
   * @generated from field: uint32 max = 3;
   */
  max: number;

  /**
   * @generated from field: repeated timetable.BusyPeriod busy_periods = 4;
   */
  busyPeriods: BusyPeriod[];

  /**
   * @generated from field: optional float commute = 5;
   */
  commute?: number;
};

/**
 * Describes the message timetable.DaySetting.
 * Use `create(DaySettingSchema)` to create a new message.
 */
export const DaySettingSchema: GenMessage<DaySetting> = /*@__PURE__*/
  messageDesc(file_backup, 9);

/**
 * @generated from message timetable.BusyPeriod
 */
export type BusyPeriod = Message<"timetable.BusyPeriod"> & {
  /**
   * @generated from field: uint32 start = 1;
   */
  start: number;

  /**
   * @generated from field: uint32 end = 2;
   */
  end: number;
};

/**
 * Describes the message timetable.BusyPeriod.
 * Use `create(BusyPeriodSchema)` to create a new message.
 */
export const BusyPeriodSchema: GenMessage<BusyPeriod> = /*@__PURE__*/
  messageDesc(file_backup, 10);

